Update imofs comment.

diff --git a/imofs b/imofs
--- a/imofs
+++ b/imofs
@@ -1,6 +1,15 @@
 #!/bin/bash
 # A command-line tool to backup/restore files and services.
 #
+# # Usage
+# ```sh
+# imofs [options] command
+# ```
+#
+# # Command
+# - restore ... Restore files and services.
+# - backup ... Backup files and services.
+#
 # This command is useful especially for programming contests giving an disk
 # image, and imofs backs up the initial state and restores almost everything.
 # Directories to backup/restore are specified as TARGETS, and services to
@@ -13,7 +22,11 @@
 # - /backup/imofs/targets ...
 #       Directories to backup/restore.  A directory should not end with "/".
 
-set -e -u
+source "$(dirname "${BASH_SOURCE}")"/imosh || exit 1
+
+DEFINE_bool dry_run --alias=n false 'Show what would have been transferred.'
+
+eval "${IMOSH_INIT}"
 
 # Top directories to backup.
 TARGETS=(bin etc home lib lib64 local opt root sbin usr var)
@@ -46,7 +59,7 @@ restart_services() {
 
 call_rsync() {
   local rsync_options=(-av --delete)
-  if (( DRY_RUN )); then
+  if (( FLAGS_dry_run )); then
     rsync_options+=(--dry-run)
   fi
   rsync "${rsync_options[@]}" "$@"
@@ -69,7 +82,7 @@ imofs::restore() {
 imofs::backup() {
   mkdir -p /backup/imofs
   echo 'Backing up services...' >&2
-  if (( ! DRY_RUN )); then
+  if (( ! FLAGS_dry_run )); then
     for service in "${SERVICES[@]}"; do
       if service "${service}" status >/dev/null 2>/dev/null; then
         echo "${service}" >>'/backup/imofs/services'
@@ -104,39 +117,11 @@ main() {
 
 # Initialize variables.
 ACTIVE_SERVICES=()
-export IFS=' \t\n'
-DRY_RUN=0
-
-# Parse flags simply.
-if [ "$#" -ne 0 ]; then
-  ARGV=()
-  for arg in "$@"; do
-    case "${arg}" in
-      --dry-run|-n) DRY_RUN=1;;
-      *)            ARGV+=("${arg}");;
-    esac
-  done
-  set -- "${ARGV[@]}"
-fi
-
-if [ "$#" -eq 1 ] && [ "$1" != 'help' ]; then
+if [ "$#" -eq 1 ] ; then
   if [ "$(whoami)" != 'root' ]; then
-    echo 'root privilege is required.' >&2
-    exit 1
+    LOG FATAL 'root privilege is required.'
   fi
   main "$1"
 else
-  cat <<EOM >&2
-Usage: imofs [options] command
-
-Commands:
-  help - Show this message.
-  restore - Restore files and services.
-  backup - Backup files and services.
-
-Options:
-  --dry-run or -n
-      Show what would have been transferred.
-EOM
-  exit 1
+  func::exit 'Command is required.'
 fi
